# DESCRIPTION: GitLab CI/CD for libRetro (NOT FOR GitLab-proper)

##############################################################################
################################# BOILERPLATE ################################
##############################################################################

# Core definitions
.core-defs:
  variables:
    GIT_SUBMODULE_STRATEGY: normal
    CORENAME: thepowdertoy
    CORE_ARGS: -DBUILD_LIBRETRO=ON
    EXTRA_PATH: src

# Inclusion templates, required for the build to work
include:
  ################################## DESKTOPS ################################    
  # Linux
  - project: 'libretro-infrastructure/ci-templates'
    file: '/linux-cmake.yml'
    
  # Windows
  - project: 'libretro-infrastructure/ci-templates'
    file: '/windows-cmake-mingw.yml'

  ################################## CELLULAR ################################    
  # Android
  - project: 'libretro-infrastructure/ci-templates'
    file: '/android-cmake.yml'

# Stages for building
stages:
  - build-prepare
  - build-shared

##############################################################################
#################################### STAGES ##################################
##############################################################################
#
################################### DESKTOPS #################################    
# Linux 64-bit
libretro-build-linux-x86_64:
  extends:
    - .libretro-linux-cmake-x86_64
    - .core-defs

# Windows 32-bit
libretro-build-windows-x86:
  extends:
    - .libretro-windows-cmake-x86
    - .core-defs

# Windows 64-bit
libretro-build-windows-x86_64:
  extends:
    - .libretro-windows-cmake-x86_64
    - .core-defs

################################### CELLULAR #################################
# Android ARMv7a
android-armeabi-v7a:
  extends:
    - .libretro-android-cmake-armeabi-v7a
    - .core-defs

# Android ARMv8a
android-arm64-v8a:
  extends:
    - .libretro-android-cmake-arm64-v8a
    - .core-defs

# Android 64-bit x86
android-x86_64:
  extends:
    - .libretro-android-cmake-x86_64
    - .core-defs

# Android 32-bit x86
android-x86:
  extends:
    - .libretro-android-cmake-x86
    - .core-defs
